/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package linguagemdeprogramacao02;

import javax.swing.JOptionPane;

/**
 *
 * @author everson.menezes
 */
public class fr_Tela_Aula02 extends javax.swing.JFrame {

    /**
     * Creates new form fr_Tela_Aula02
     */
    public int idade;
    public double nota;
    public fr_Tela_Aula02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JToggleButton();
        btnSalvar = new javax.swing.JToggleButton();
        chkManha = new javax.swing.JCheckBox();
        chkNoite = new javax.swing.JCheckBox();
        cbxCurso = new javax.swing.JComboBox<>();
        txtNome = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Período");

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        chkManha.setText("Manhã");
        chkManha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkManhaActionPerformed(evt);
            }
        });

        chkNoite.setText("Noite");
        chkNoite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNoiteActionPerformed(evt);
            }
        });

        cbxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Informática", "Administraão", "Automação" }));

        jLabel1.setText("Nome");

        jLabel2.setText("Idade");

        jLabel3.setText("Curso");

        jLabel5.setText("Senha");

        jLabel6.setText("Email");

        jLabel7.setText("Nota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(btnSalvar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(chkManha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkNoite))
                    .addComponent(cbxCurso, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(33, 33, 33)
                        .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSenha))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkManha)
                        .addComponent(chkNoite)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnSalvar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtNome.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null,"Preencha o Nome","ERRO Nome",JOptionPane.ERROR_MESSAGE);
       } else {
           
           if (txtNome.getText().trim().length()<10) {
              JOptionPane.showMessageDialog(null,"Tamanho Mínimo para o Nome de 10 Caracteres","ERRO Nome",JOptionPane.ERROR_MESSAGE);
           }
       } 
       
       if (txtSenha.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null,"Preencha o Email","ERRO Email",JOptionPane.ERROR_MESSAGE);
       }  else {
         String email = txtEmail.getText().trim();
         int posArroba = email.indexOf('@');
         
         
         if ((!email.endsWith(".gov.br"))&&
             (!email.endsWith(".com.br"))&&
             (!email.endsWith(".com"))
            ) 
         {
            JOptionPane.showMessageDialog(null,"Domínio do email Inválido","ERRO Email",JOptionPane.ERROR_MESSAGE);
         }
         
         if ((email.startsWith("_"))||(email.startsWith("#"))||(email.startsWith("&")))
         {
            JOptionPane.showMessageDialog(null,"Inicio do Email Inválido","ERRO Email",JOptionPane.ERROR_MESSAGE);
         }
         
           
       }
       
       if (txtIdade.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null,"Preencha o Idade","ERRO Idade",JOptionPane.ERROR_MESSAGE);
       } 
       
       if (txtSenha.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null,"Preencha o Senha","ERRO Senha",JOptionPane.ERROR_MESSAGE);
       }  else {
           if ((txtSenha.getText().trim().length()<8)||(txtSenha.getText().trim().length()>12)) {
              JOptionPane.showMessageDialog(null,"Senha deve ter entre 8 e  12 Caracteres","ERRO Senha",JOptionPane.ERROR_MESSAGE);
           }
       }
       
       if (txtNota.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null,"Preencha a Nota ","ERRO Nota",JOptionPane.ERROR_MESSAGE);
       } 
       
       if((!chkNoite.isSelected())&&(!chkManha.isSelected())) {
            JOptionPane.showMessageDialog(null,"Selecione um dos Periodos","ERRO Periodo",JOptionPane.ERROR_MESSAGE);
       }
       
       if(cbxCurso.getSelectedIndex()== 0) {
           JOptionPane.showMessageDialog(null,"Selecione um Curso","ERRO Curso",JOptionPane.ERROR_MESSAGE);
       }
       
       try {
          idade = Integer.parseInt(txtIdade.getText().trim());  
          nota = Double.parseDouble(txtNota.getText().trim());
          
       } catch (NumberFormatException erro ) {
           JOptionPane.showMessageDialog(null,"Digite apenas Números em Idade/Nota Vestibular\n"+erro.getMessage(),"ERRO Tratamento Numéricos",JOptionPane.ERROR_MESSAGE);
       }
       
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNome.setText(null);
        txtIdade.setText(null);
        chkManha.setSelected(false);
        chkNoite.setSelected(false);
        cbxCurso.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void chkManhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkManhaActionPerformed
        chkManha.setSelected(true);
        chkNoite.setSelected(false);
    }//GEN-LAST:event_chkManhaActionPerformed

    private void chkNoiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNoiteActionPerformed
        chkManha.setSelected(false);
        chkNoite.setSelected(true);
    }//GEN-LAST:event_chkNoiteActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_Tela_Aula02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_Tela_Aula02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_Tela_Aula02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_Tela_Aula02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_Tela_Aula02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLimpar;
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.JComboBox<String> cbxCurso;
    private javax.swing.JCheckBox chkManha;
    private javax.swing.JCheckBox chkNoite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
